version: '3.1'

services:
  node:
    image: node:18.12


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 6iQ&7k5DRHA1HQz!
    networks:
      - asa-default-network
  
  auto-site-audit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18002:1338
    networks:
      - asa-default-network
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:6iQ%267k5DRHA1HQz!@mongo:27017/?authMechanism=DEFAULT
      AUDIT_THREAD_POOL_COUNT: 3
    depends_on:
      - mongo

networks:
  asa-default-network:
    driver: bridge