POST {{host}}api/scrape HTTP/1.1
Content-Type: application/json

{
	"urls": [
		"pvcase.com",
		"fellowship.agency",
		"optimamedia.nl",
		"polkandunion.com",
		"giraffesocialmedia.co.uk",
		"jointlondon.com",
		"rca.be",
		"rhinogroup.co.uk",
		"visarc.uk",
		"equinetmedia.com",
		"be-hookd.com",
		"offlinemarketing.co.uk",
		"nestcommerce.co",
		"cashcowmarketing.co.uk",
		"eco-n-tech.com",
		"blendcommerce.com",
		"blackcamel.agency",
		"capitalblock.io",
		"fortyeight.one",
		"happy.fb.se",
		"newson.io",
		"stadamedia.co.uk",
		"startupvoyager.com",
		"key-content.com",
		"youlynq.me",
		"wearefyi.co.uk",
		"online.sovendus.com",
		"funnelboost.co.uk",
		"indigotree.co.uk",
		"beanstalkmarketing.co.uk",
		"curated-digital.com",
		"romablack.com",
		"blinkseo.co.uk",
		"aip.media",
		"connectmgt.com",
		"insight.berlin",
		"dapperrhinos.com",
		"immediatefuture.co.uk",
		"brave.agency",
		"distributedigital.co.uk",
		"themarketingcentre.com",
		"reachinout.co.uk",
		"mantrahq.com",
		"bigfootdigital.co.uk",
		"reddotgrowth.com",
		"8thdial.com",
		"brightsparksagency.co.uk",
		"thegeneration.se",
		"vmistudio.com",
		"lingner.com"
	]
}